package com.github.leftisttachyon.gui;

import com.github.leftisttachyon.input.InvalidFileFormatException;
import com.github.leftisttachyon.input.SimpleInstruction;
import com.github.leftisttachyon.input.SimplePlayback;
import com.github.leftisttachyon.input.compiled.CompiledPlayback;
import lombok.extern.slf4j.Slf4j;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.NumberFormat;
import java.util.ArrayList;

/**
 * The main GUI window
 *
 * @author Jed Wang
 * @since 1.0.0
 */
@Slf4j
public final class MainFrame extends JFrame {

    /**
     * The list of tabs
     */
    private final ArrayList<FileTab> tabs;
    /**
     * The {@link JFileChooser} instance used in this {@link MainFrame}.
     */
    private final JFileChooser fc;
    /**
     * A {@link JTabbedPane} that contains all of the goods
     */
    private JTabbedPane fileTabbedPane;
    /**
     * A formatted text field that handles the x-offset
     */
    private JFormattedTextField xOffsetField;
    /**
     * A formatted text field that handles the y-offset
     */
    private JFormattedTextField yOffsetField;
    /**
     * A counter for unnamed files
     */
    private int cnt = 2;

    /**
     * Creates a new MainFrame
     */
    public MainFrame() {
        tabs = new ArrayList<>();
        fc = new JFileChooser();

        initComponents();
    }

    /**
     * Creates and shows this MainFrame for testing purposes.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            log.error("Cannot start application", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JLabel xOffsetLabel = new JLabel();
        NumberFormat coordinateFormat = NumberFormat.getNumberInstance();
        coordinateFormat.setMinimumIntegerDigits(1);
        xOffsetField = new JFormattedTextField(coordinateFormat);
        fileTabbedPane = new JTabbedPane();
        JLabel yOffsetLabel = new JLabel();
        yOffsetField = new JFormattedTextField(coordinateFormat);
        JMenuBar menuBar = new JMenuBar();
        JMenu fileMenu = new JMenu();
        JMenuItem newMenuItem = new JMenuItem();
        JMenuItem openMenuItem = new JMenuItem();
        JMenuItem saveMenuItem = new JMenuItem();
        JMenuItem saveAsMenuItem = new JMenuItem();
        JMenuItem saveAllMenuItem = new JMenuItem();
        JPopupMenu.Separator separator1 = new JPopupMenu.Separator();
        JMenuItem exitMenuItem = new JMenuItem();
        JMenu editMenu = new JMenu();
        JMenuItem includeFileMenuItem = new JMenuItem();
        JMenu viewMenu = new JMenu();
        JMenuItem closeTabMenuItem = new JMenuItem();
        JMenuItem closeAllTabsMenuItem = new JMenuItem();
        JPopupMenu.Separator seperator2 = new JPopupMenu.Separator();
        JCheckBoxMenuItem lineNumCheckBox = new JCheckBoxMenuItem();
        JCheckBoxMenuItem frameNumCheckBox = new JCheckBoxMenuItem();
        JMenu runMenu = new JMenu();
        JMenuItem circleTestMenuItem = new JMenuItem();
        JMenuItem runMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("RhoIda");

        Font segoe12 = new Font("Segoe UI", Font.PLAIN, 12); // NOI18N
        xOffsetLabel.setFont(segoe12);
        xOffsetLabel.setText("X offset:");

        xOffsetField.setFont(segoe12);
        xOffsetField.setText("0");

        fileTabbedPane.setFont(new Font("Monospace", Font.PLAIN, 11)); // NOI18N
        fileTabbedPane.addTab("unsaved1", newFileTab());

        yOffsetLabel.setFont(segoe12);
        yOffsetLabel.setText("Y offset:");

        yOffsetField.setFont(segoe12);
        yOffsetField.setText("0");

        fileMenu.setText("File");
        newMenuItem.setAccelerator(KeyStroke.getKeyStroke("control N"));
        newMenuItem.setText("New");
        newMenuItem.addActionListener(this::create);
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(KeyStroke.getKeyStroke("control O"));
        openMenuItem.setText("Open...");
        openMenuItem.addActionListener(this::open);
        fileMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(KeyStroke.getKeyStroke("control S"));
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(this::save);
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As...");
        saveAsMenuItem.addActionListener(this::saveAs);
        fileMenu.add(saveAsMenuItem);

        saveAllMenuItem.setAccelerator(KeyStroke.getKeyStroke("control shift S"));
        saveAllMenuItem.setText("Save All");
        saveAllMenuItem.addActionListener(this::saveAll);
        fileMenu.add(saveAllMenuItem);
        fileMenu.add(separator1);

        exitMenuItem.setAccelerator(KeyStroke.getKeyStroke("alt F4"));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(this::exit);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        includeFileMenuItem.setAccelerator(KeyStroke.getKeyStroke("control I"));
        includeFileMenuItem.setText("Include File...");
        includeFileMenuItem.addActionListener(this::insertInclude);
        editMenu.add(includeFileMenuItem);

        menuBar.add(editMenu);

        viewMenu.setText("View");

        closeTabMenuItem.setAccelerator(KeyStroke.getKeyStroke("control W"));
        closeTabMenuItem.setText("Close Tab");
        closeTabMenuItem.addActionListener(this::closeTab);
        viewMenu.add(closeTabMenuItem);

        closeAllTabsMenuItem.setAccelerator(KeyStroke.getKeyStroke("control shift W"));
        closeAllTabsMenuItem.setText("Close All Tabs");
        closeAllTabsMenuItem.addActionListener(this::closeAllTabs);
        viewMenu.add(closeAllTabsMenuItem);
        viewMenu.add(seperator2);

        lineNumCheckBox.setSelected(true);
        lineNumCheckBox.setText("Enable Line Numbers");
        lineNumCheckBox.addActionListener(this::toggleLineNums);
        viewMenu.add(lineNumCheckBox);

        frameNumCheckBox.setSelected(true);
        frameNumCheckBox.setText("Enable Frame Numbers");
        frameNumCheckBox.addActionListener(this::toggleFrameNums);
        viewMenu.add(frameNumCheckBox);

        menuBar.add(viewMenu);

        runMenu.setText("Run");

        circleTestMenuItem.setAccelerator(KeyStroke.getKeyStroke("F5"));
        circleTestMenuItem.setText("Circle Test");
        circleTestMenuItem.addActionListener(this::runCircleTest);
        runMenu.add(circleTestMenuItem);

        runMenuItem.setAccelerator(KeyStroke.getKeyStroke("F6"));
        runMenuItem.setText("Run");
        runMenuItem.addActionListener(this::run);
        runMenu.add(runMenuItem);

        menuBar.add(runMenu);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(xOffsetLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xOffsetField, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yOffsetLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yOffsetField, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 154, Short.MAX_VALUE))
                                .addComponent(fileTabbedPane))
                        .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(xOffsetLabel)
                                .addComponent(xOffsetField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(yOffsetLabel)
                                .addComponent(yOffsetField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileTabbedPane, GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void open(ActionEvent evt) {
        int returnVal = fc.showOpenDialog(this);
        log.trace("Open dialog returned {}", returnVal);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            int alreadyOpened = -1;
            for (int i = 0; i < tabs.size(); i++) {
                if (file.getName().equals(tabs.get(i).getFileName())) {
                    alreadyOpened = i;
                    break;
                }
            }

            if (alreadyOpened != -1) {
                fileTabbedPane.setSelectedIndex(alreadyOpened);
            } else {
                FileTab fileTab = newFileTab(file);
                if (fileTab != null) {
                    fileTabbedPane.addTab(file.getName(), fileTab);
                    fileTabbedPane.setSelectedIndex(fileTabbedPane.getTabCount() - 1);
                }
            }
        }
    }

    private void save(ActionEvent evt) {
        FileTab selectedTab = getSelectedTab();
        if (selectedTab.getFile() == null) {
            saveAs(evt);
        } else {
            if (!selectedTab.save()) {
                JOptionPane.showMessageDialog(this, "This file could not be saved", "Save failed",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void create(ActionEvent evt) {
        fileTabbedPane.addTab("unsaved" + (cnt++), newFileTab());
        fileTabbedPane.setSelectedIndex(fileTabbedPane.getTabCount() - 1);
    }

    private void toggleLineNums(ActionEvent evt) {
        getSelectedTab().toggleLineNums();
    }

    private void saveAs(ActionEvent evt) {
        int returnVal = fc.showSaveDialog(this);
        log.trace("Save dialog returned {}", returnVal);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            FileTab selectedTab = getSelectedTab();
            selectedTab.setFile(file);
            fileTabbedPane.setTitleAt(fileTabbedPane.getSelectedIndex(),
                    selectedTab.getFileName());
            if (!selectedTab.save()) {
                JOptionPane.showMessageDialog(this, "This file could not be saved", "Save failed",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void saveAll(ActionEvent evt) {
        for (int i = 0; i < tabs.size(); i++) {
            FileTab tab = tabs.get(i);
            if (tab.getFile() == null) {
                fileTabbedPane.setSelectedIndex(i);
                saveAs(evt);
            } else {
                if (!tab.save()) {
                    JOptionPane.showMessageDialog(this, tab.getFileName() + " could not be saved", "Save failed",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void exit(ActionEvent evt) {
        closeAllTabs(evt);
        dispose();
        System.exit(0);
    }

    private void insertInclude(ActionEvent evt) {
        save(evt);

        int returnVal = fc.showOpenDialog(this);
        log.trace("Open dialog returned {}", returnVal);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            FileTab fileTab = newFileTab(file);
            if (fileTab != null) {
                FileTab selectedTab = getSelectedTab();
                if (selectedTab.getFile().equals(file)) {
                    JOptionPane.showMessageDialog(this, "Cannot include self", "Invalid inclusion",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    boolean alreadyOpened = false;
                    for (FileTab tab : tabs) {
                        if (tab.getFileName().equals(file.getName())) {
                            alreadyOpened = true;
                            break;
                        }
                    }
                    if (!alreadyOpened) {
                        fileTabbedPane.addTab(file.getName(), fileTab);
                    }
                    String relLocation = file.toURI()
                            .relativize(selectedTab.getFile().toURI()).getPath();
                    selectedTab.insertAtCursor("INCLUDE " + relLocation + '\n');
                }
            }
        }
    }

    private void toggleFrameNums(ActionEvent evt) {
        getSelectedTab().toggleFrameNums();
    }

    private void runCircleTest(ActionEvent evt) {
        save(evt);

        int x = Integer.parseInt(xOffsetField.getText()),
                y = Integer.parseInt(yOffsetField.getText());
        SimpleInstruction.setX_OFFSET(x);
        SimpleInstruction.setY_OFFSET(y);

        // TODO: window
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private void run(ActionEvent evt) {
        save(evt);

        int x = Integer.parseInt(xOffsetField.getText()),
                y = Integer.parseInt(yOffsetField.getText());
        SimpleInstruction.setX_OFFSET(x);
        SimpleInstruction.setY_OFFSET(y);

        File file = getSelectedTab().getFile();
        SimplePlayback uncompiled;
        CompiledPlayback compiled;
        try {
            SimplePlayback.clearCache();
            uncompiled = SimplePlayback.createPlayback(file);
            compiled = uncompiled.compile();
        } catch (InvalidFileFormatException ife) {
            JOptionPane.showMessageDialog(this, "The format of the file was incorrect:\n" + ife.getMessage(),
                    "Badly formatted file", JOptionPane.WARNING_MESSAGE);
            log.info("InvalidFileFormatException was thrown", ife);
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Please check the data of the file:\n" + nfe.getMessage(),
                    "Badly file data", JOptionPane.WARNING_MESSAGE);
            log.info("NumberFormatException was thrown", nfe);
            return;
        }

        try {
            compiled.execute(new Robot(), 16);
        } catch (AWTException e) {
            log.warn("An exception was thrown while creating a Robot", e);
        }
    }

    private void closeTab(ActionEvent evt) {
        int temp = fileTabbedPane.getSelectedIndex();
        FileTab selectedTab = getSelectedTab();
        if (selectedTab.getFile() == null || selectedTab.isChanged()) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure that you want to close this without saving?",
                    "Closing confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == 1) {
                return;
            }
        }
        fileTabbedPane.remove(temp);
        tabs.remove(temp);
        fileTabbedPane.setSelectedIndex(Math.min(temp, fileTabbedPane.getTabCount() - 1));

        if (fileTabbedPane.getTabCount() == 0) {
            create(evt);
        }
    }

    private void closeAllTabs(ActionEvent evt) {
        int tabCount = fileTabbedPane.getTabCount();
        log.debug("Tab count: {}", tabCount);
        for (int i = 0; i < tabCount; i++) {
            fileTabbedPane.remove(0);
        }
        tabs.clear();

        create(evt);
    }

    private FileTab newFileTab() {
        FileTab tab = new FileTab();
        tabs.add(tab);
        return tab;
    }

    private FileTab newFileTab(File f) {
        FileTab tab;
        try {
            tab = new FileTab(f);
        } catch (RuntimeException re) {
            return null;
        }
        tabs.add(tab);
        return tab;
    }

    private FileTab getSelectedTab() {
        int idx = fileTabbedPane.getSelectedIndex();
        return tabs.get(idx);
    }
    // End of variables declaration
}
